import { BASEHEADERS } from '@/constants';
import { NextResponse } from 'next/server';

/**
:method: POST
:path: /graphql/query/react-native/player-sort-stats
:authority: www.dream11.com
:scheme: https
accept: application/json
device: androidplaystore
devicetype: ANDROID
deviceid: 2d016ea7f014d06c
ek1: 1baaed3d74f4a9d3e015539e9e57e52e3628b5eacd96f7e4fb42be4ef92153d9
ek2: 1baaed3d74f4a9d3e015539e9e57e52e3628b5eacd96f7e4fb42be4ef92153d9
x-manufacturer: google
x-os-version: 16
x-os-type: android
x-app-version-name: 750
app_version: 7.5.0
a1: b4581fbf01c51d18e8c85cc70ed1b60f7e4467ade5695bfbc25b50e5b0cc84f5
version: 10045
user-agent: Dream11/7.5.0 (Linux; Android 36; Pixel 6a) Build/10045
siteid: 1
locale: en-US
authorization: Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsInR5cCI6ImF0K2p3dCIsImtpZCI6IlRqb0FsLVdyZWN3Z3MtZVVvcm5xWWE5Y2x4dyJ9.eyJhdWQiOiJhOEVzRGxQYzNaQ1Znc1VwcHB1YyIsImV4cCI6MTc3MzY3NzY5NiwiaWF0IjoxNzczNTkxMjk2LCJpc3MiOiJkcmVhbTExLmNvbSIsInN1YiI6IjMxNzE1MjMzMCIsImp0aSI6ImhtT2tmc0NCQVM5d2JkQUhiSDVva3lCOW84OVpqdVRRIiwidGlkIjoiMiIsInJmdF9pZCI6IjBGQkFEMUQ5RjFENzdGOTlFQjdFNzAzM0IzQ0RFREVGIiwiY2xpZW50X2lkIjoiYThFc0RsUGMzWkNWZ3NVcHBwdWMiLCJzY29wZSI6ImRyZWFtMTE6YWxsIiwiYW1yIjpbIm90cCJdLCJjb3VudHJ5Q29kZSI6IklOIn0.iZVontVwx0-WkQErCRaKQ9Eum31miMaGnsO1uO4KOiuKxnGxl2nx_guM8k4pL0R8R7WRhTebkXXlC-WUb039AGU0kq6U-Hafrx40Pss3bsJ76AKG8Ygi8SN38-D3g-oXanhGdnnH0NPuoVDCUfBL5M9UmkIzvH_VwPOoJFCBRtsNoNzmmIN5Ef-YhdNi8sb2fvuXnIkzekJ0KbhxtpCTA6xcrFn3uemmJPyhyzg6lDU4pvDYAGpDiJh0GTnk1RXtDj9qqkloX4jSrJ5HQkqIBUlTtEKykImGSJz9ob-oXbpkajc0kcQKrCltfclX0eOHPHy98lQTgpvOtg6ulY6nvQ
content-type: application/json
content-length: 477
accept-encoding: gzip

{"query":"\n    query PlayerSortStats($site: String!, $matchId: Int!) {\n  match(site: $site, id: $matchId) {\n    allStats {\n      defaultStat\n      statFilterEnabled\n      statInfo {\n        statLevel\n        shortDisplayName\n        displayName\n        statType\n        displayOn\n      }\n      stats {\n        playerId\n        stats {\n          statType\n          value\n        }\n      }\n    }\n  }\n}\n    ","variables":{"site":"cricket","matchId":112992}}

{
	"query": "\n    query PlayerSortStats($site: String!, $matchId: Int!) {\n  match(site: $site, id: $matchId) {\n    allStats {\n      defaultStat\n      statFilterEnabled\n      statInfo {\n        statLevel\n        shortDisplayName\n        displayName\n        statType\n        displayOn\n      }\n      stats {\n        playerId\n        stats {\n          statType\n          value\n        }\n      }\n    }\n  }\n}\n    ",
	"variables": {
		"site": "cricket",
		"matchId": 113005
	}
}

*/
export async function POST(request: Request) {
	const body = await request.json();
	const { query, variables } = body;
	
	if (process.env.WWW_GRAPHAL_URL) {
		// Use real API to fetch data
		try {
			const apiURL = process.env.WWW_GRAPHAL_URL + "/graphql/query/react-native/player-sort-stats";
			const response = await fetch(apiURL, {
				method: 'POST',
				headers: BASEHEADERS,
				body: JSON.stringify({
					query,
					variables
				}),
				// Next.js 特有缓存配置：每 60 秒刷新一次数据
				next: { revalidate: 60 }
			});
			
			if (!response.ok) {
				throw new Error(`API request failed: ${response.status}, url: ${apiURL}, headers: ${JSON.stringify(BASEHEADERS)}`);
			}
			
			const data = await response.json();
			return NextResponse.json(data);
		} catch (error) {
			console.error('API request error:', error);
			// Fall back to mock data if API fails
		}
	}
	
	return NextResponse.json({
		"data": {
			"match": {
				"allStats": {
					"defaultStat": "TOTAL_POINTS",
					"statFilterEnabled": true,
					"statInfo": [{
						"statLevel": "ROUND",
						"shortDisplayName": "Credits",
						"displayName": "Credits",
						"statType": "CREDITS",
						"displayOn": ["SPCT", "BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "ROUND",
						"shortDisplayName": "% Sel by",
						"displayName": "% Selected By",
						"statType": "PLAYER_SELECTION_PERCENTAGE",
						"displayOn": ["BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "TOUR",
						"shortDisplayName": "Points",
						"displayName": "Points",
						"statType": "TOTAL_POINTS",
						"displayOn": ["CT", "SPCT", "CVC", "BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "TOUR",
						"shortDisplayName": "Runs",
						"displayName": "Runs",
						"statType": "TOTAL_RUNS",
						"displayOn": ["SPCT", "CT", "BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "TOUR",
						"shortDisplayName": "Wickets",
						"displayName": "Wickets",
						"statType": "TOTAL_WICKETS",
						"displayOn": ["SPCT", "CT", "BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "TOUR",
						"shortDisplayName": "Avg Pts",
						"displayName": "Average Points",
						"statType": "AVG_POINTS",
						"displayOn": ["SPCT", "CT", "BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "ROUND",
						"shortDisplayName": "% C",
						"displayName": "% Captain By",
						"statType": "CAPTAIN_SELECTION_PERCENT",
						"displayOn": ["SPCT", "CT", "CVC", "BACKUPS", "SPCTCAT"]
					}, {
						"statLevel": "ROUND",
						"shortDisplayName": "% VC",
						"displayName": "% Vice Captain By",
						"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
						"displayOn": ["CVC"]
					}],
					"stats": [{
						"playerId": "167900",
						"stats": [{
							"statType": "CREDITS",
							"value": "6.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "12.68"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "74"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "23"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "1"
						}, {
							"statType": "AVG_POINTS",
							"value": "37"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.52"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.74"
						}]
					}, {
						"playerId": "179557",
						"stats": [{
							"statType": "CREDITS",
							"value": "9"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "84.82"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "160"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "18"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "3"
						}, {
							"statType": "AVG_POINTS",
							"value": "80"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "5.57"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "8.25"
						}]
					}, {
						"playerId": "192059",
						"stats": [{
							"statType": "CREDITS",
							"value": "7"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "0.41"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "0"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "0"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "0"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.03"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.03"
						}]
					}, {
						"playerId": "12059",
						"stats": [{
							"statType": "CREDITS",
							"value": "9"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "89.13"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "208"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "64"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "3"
						}, {
							"statType": "AVG_POINTS",
							"value": "104"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "12.03"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "13.73"
						}]
					}, {
						"playerId": "14258",
						"stats": [{
							"statType": "CREDITS",
							"value": "8"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "82.35"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "275"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "26"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "5"
						}, {
							"statType": "AVG_POINTS",
							"value": "137.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "12.75"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "18.69"
						}]
					}, {
						"playerId": "18071",
						"stats": [{
							"statType": "CREDITS",
							"value": "8.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "10.88"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "31"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "17"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "31"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.33"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.49"
						}]
					}, {
						"playerId": "18072",
						"stats": [{
							"statType": "CREDITS",
							"value": "9"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "31.03"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "66"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "5"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "1"
						}, {
							"statType": "AVG_POINTS",
							"value": "33"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "1.27"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "1.55"
						}]
					}, {
						"playerId": "27659",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "0.75"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "42"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "20"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "42"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.04"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.04"
						}]
					}, {
						"playerId": "44689",
						"stats": [{
							"statType": "CREDITS",
							"value": "8.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "90.75"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "291"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "33"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "6"
						}, {
							"statType": "AVG_POINTS",
							"value": "145.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "35.49"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "12.93"
						}]
					}, {
						"playerId": "97815",
						"stats": [{
							"statType": "CREDITS",
							"value": "6.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "51.26"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "140"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "46"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "1"
						}, {
							"statType": "AVG_POINTS",
							"value": "70"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "1.20"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "1.97"
						}]
					}, {
						"playerId": "97740",
						"stats": [{
							"statType": "CREDITS",
							"value": "7"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "8.99"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "72"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "17"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "1"
						}, {
							"statType": "AVG_POINTS",
							"value": "72"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.31"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.45"
						}]
					}, {
						"playerId": "20473",
						"stats": [{
							"statType": "CREDITS",
							"value": "7"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "13.28"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "36"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "12"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "18"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.65"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.65"
						}]
					}, {
						"playerId": "82547",
						"stats": [{
							"statType": "CREDITS",
							"value": "8"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "70.83"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "76"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "28"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "38"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "2.65"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "2.55"
						}]
					}, {
						"playerId": "97801",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "0.48"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "0"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "0"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "0"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.05"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.05"
						}]
					}, {
						"playerId": "145665",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "1.11"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "0"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "0"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "0"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.09"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.10"
						}]
					}, {
						"playerId": "97808",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "44.93"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "72"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "34"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "36"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "1.54"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "1.86"
						}]
					}, {
						"playerId": "25535",
						"stats": [{
							"statType": "CREDITS",
							"value": "9"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "78.47"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "159"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "87"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "79.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "4.17"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "4.64"
						}]
					}, {
						"playerId": "121368",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "15.15"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "48"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "12"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "24"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.87"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "1.03"
						}]
					}, {
						"playerId": "121443",
						"stats": [{
							"statType": "CREDITS",
							"value": "8"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "59.43"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "147"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "91"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "73.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "2.16"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "2.93"
						}]
					}, {
						"playerId": "4158",
						"stats": [{
							"statType": "CREDITS",
							"value": "8.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "19.32"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "32"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "24"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "32"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "1.05"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "1.28"
						}]
					}, {
						"playerId": "149346",
						"stats": [{
							"statType": "CREDITS",
							"value": "6.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "68.41"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "193"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "18"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "3"
						}, {
							"statType": "AVG_POINTS",
							"value": "96.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "3.21"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "3.55"
						}]
					}, {
						"playerId": "44683",
						"stats": [{
							"statType": "CREDITS",
							"value": "8"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "1.45"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "0"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "0"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "0"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.09"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.09"
						}]
					}, {
						"playerId": "145432",
						"stats": [{
							"statType": "CREDITS",
							"value": "7"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "0.66"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "14"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "6"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "14"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.04"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.04"
						}]
					}, {
						"playerId": "106835",
						"stats": [{
							"statType": "CREDITS",
							"value": "8.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "5.52"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "116"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "0"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "3"
						}, {
							"statType": "AVG_POINTS",
							"value": "116"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.31"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.38"
						}]
					}, {
						"playerId": "106837",
						"stats": [{
							"statType": "CREDITS",
							"value": "8"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "75.83"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "226"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "52"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "3"
						}, {
							"statType": "AVG_POINTS",
							"value": "113"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "4.08"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "7.45"
						}]
					}, {
						"playerId": "121367",
						"stats": [{
							"statType": "CREDITS",
							"value": "9"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "67.02"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "190"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "36"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "3"
						}, {
							"statType": "AVG_POINTS",
							"value": "190"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "2.87"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "4.05"
						}]
					}, {
						"playerId": "179558",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "17.37"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "112"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "1"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "2"
						}, {
							"statType": "AVG_POINTS",
							"value": "56"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.44"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.70"
						}]
					}, {
						"playerId": "182856",
						"stats": [{
							"statType": "CREDITS",
							"value": "7"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "0.31"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "0"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "0"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "0"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.02"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.02"
						}]
					}, {
						"playerId": "11229",
						"stats": [{
							"statType": "CREDITS",
							"value": "8.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "83.63"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "237"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "12"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "5"
						}, {
							"statType": "AVG_POINTS",
							"value": "118.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "6"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "9.45"
						}]
					}, {
						"playerId": "97807",
						"stats": [{
							"statType": "CREDITS",
							"value": "7.50"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "1.49"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "17"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "3"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "17"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.03"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.05"
						}]
					}, {
						"playerId": "109469",
						"stats": [{
							"statType": "CREDITS",
							"value": "7"
						}, {
							"statType": "PLAYER_SELECTION_PERCENTAGE",
							"value": "12.42"
						}, {
							"statType": "TOTAL_POINTS",
							"value": "33"
						}, {
							"statType": "TOTAL_RUNS",
							"value": "13"
						}, {
							"statType": "TOTAL_WICKETS",
							"value": "0"
						}, {
							"statType": "AVG_POINTS",
							"value": "16.50"
						}, {
							"statType": "CAPTAIN_SELECTION_PERCENT",
							"value": "0.28"
						}, {
							"statType": "VICE_CAPTAIN_SELECTION_PERCENT",
							"value": "0.42"
						}]
					}]
				}
			}
		}
	});
}
