import { NextResponse } from 'next/server';

// /countries?active=true
export async function GET() {
	return NextResponse.json({
		"countries": [{
			"countryId": 41,
			"countryCode": "CA",
			"country": "Canada",
			"telephoneCode": "+1",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 61,
			"countryCode": "AU",
			"country": "Australia",
			"telephoneCode": "+61",
			"countryFlag": "AUS-CR1",
			"active": true
		}, {
			"countryId": 114,
			"countryCode": "IN",
			"country": "India",
			"telephoneCode": "+91",
			"countryFlag": "IND-CR1",
			"active": true
		}, {
			"countryId": 247,
			"countryCode": "US",
			"country": "USA",
			"telephoneCode": "+1",
			"countryFlag": "USA-CR1",
			"active": true
		}, {
			"countryId": 251,
			"countryCode": "AL",
			"country": "Albania",
			"telephoneCode": "+355",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 252,
			"countryCode": "DZ",
			"country": "Algeria",
			"telephoneCode": "+213",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 254,
			"countryCode": "AD",
			"country": "Andorra",
			"telephoneCode": "+376",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 255,
			"countryCode": "AO",
			"country": "Angola",
			"telephoneCode": "+244",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 258,
			"countryCode": "AG",
			"country": "Antigua And Barbuda",
			"telephoneCode": "+1-268",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 259,
			"countryCode": "AR",
			"country": "Argentina",
			"telephoneCode": "+54",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 260,
			"countryCode": "AM",
			"country": "Armenia",
			"telephoneCode": "+374",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 262,
			"countryCode": "AT",
			"country": "Austria",
			"telephoneCode": "+43",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 263,
			"countryCode": "AZ",
			"country": "Azerbaijan",
			"telephoneCode": "+994",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 264,
			"countryCode": "BS",
			"country": "Bahamas",
			"telephoneCode": "+1-242",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 265,
			"countryCode": "BH",
			"country": "Bahrain",
			"telephoneCode": "+973",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 266,
			"countryCode": "BD",
			"country": "Bangladesh",
			"telephoneCode": "+880",
			"countryFlag": "BAN-CR1",
			"active": true
		}, {
			"countryId": 267,
			"countryCode": "BB",
			"country": "Barbados",
			"telephoneCode": "+1-246",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 268,
			"countryCode": "BY",
			"country": "Belarus",
			"telephoneCode": "+375",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 269,
			"countryCode": "BE",
			"country": "Belgium",
			"telephoneCode": "+32",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 270,
			"countryCode": "BZ",
			"country": "Belize",
			"telephoneCode": "+501",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 271,
			"countryCode": "BJ",
			"country": "Benin",
			"telephoneCode": "+229",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 273,
			"countryCode": "BT",
			"country": "Bhutan",
			"telephoneCode": "+975",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 274,
			"countryCode": "BO",
			"country": "Bolivia",
			"telephoneCode": "+591",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 276,
			"countryCode": "BA",
			"country": "Bosnia And Herzegovina",
			"telephoneCode": "+387",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 277,
			"countryCode": "BW",
			"country": "Botswana",
			"telephoneCode": "+267",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 279,
			"countryCode": "BR",
			"country": "Brazil",
			"telephoneCode": "+55",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 280,
			"countryCode": "BN",
			"country": "Brunei Darussalam",
			"telephoneCode": "+673",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 281,
			"countryCode": "BG",
			"country": "Bulgaria",
			"telephoneCode": "+359",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 282,
			"countryCode": "BF",
			"country": "Burkina Faso",
			"telephoneCode": "+226",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 283,
			"countryCode": "BI",
			"country": "Burundi",
			"telephoneCode": "+257",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 284,
			"countryCode": "KH",
			"country": "Cambodia",
			"telephoneCode": "+855",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 285,
			"countryCode": "CM",
			"country": "Cameroon",
			"telephoneCode": "+237",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 287,
			"countryCode": "CV",
			"country": "Cape Verde",
			"telephoneCode": "+238",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 289,
			"countryCode": "CF",
			"country": "Central African Republic",
			"telephoneCode": "+236",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 290,
			"countryCode": "TD",
			"country": "Chad",
			"telephoneCode": "+235",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 291,
			"countryCode": "CL",
			"country": "Chile",
			"telephoneCode": "+56",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 295,
			"countryCode": "CO",
			"country": "Colombia",
			"telephoneCode": "+57",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 296,
			"countryCode": "KM",
			"country": "Comoros",
			"telephoneCode": "+269",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 297,
			"countryCode": "CG",
			"country": "Congo",
			"telephoneCode": "+242",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 298,
			"countryCode": "CD",
			"country": "Democratic Republic Of The Congo",
			"telephoneCode": "+243",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 300,
			"countryCode": "CR",
			"country": "Costa Rica",
			"telephoneCode": "+506",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 301,
			"countryCode": "HR",
			"country": "Croatia",
			"telephoneCode": "+385",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 304,
			"countryCode": "CY",
			"country": "Cyprus",
			"telephoneCode": "+357",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 305,
			"countryCode": "CZ",
			"country": "Czech Republic",
			"telephoneCode": "+420",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 306,
			"countryCode": "CI",
			"country": "Cote D'Ivoire",
			"telephoneCode": "+225",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 307,
			"countryCode": "DK",
			"country": "Denmark",
			"telephoneCode": "+45",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 308,
			"countryCode": "DJ",
			"country": "Djibouti",
			"telephoneCode": "+253",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 309,
			"countryCode": "DM",
			"country": "Dominica",
			"telephoneCode": "+1-767",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 310,
			"countryCode": "DO",
			"country": "Dominican Republic",
			"telephoneCode": "+1-809",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 311,
			"countryCode": "EC",
			"country": "Ecuador",
			"telephoneCode": "+593",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 312,
			"countryCode": "EG",
			"country": "Egypt",
			"telephoneCode": "+20",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 313,
			"countryCode": "SV",
			"country": "El Salvador",
			"telephoneCode": "+503",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 314,
			"countryCode": "GQ",
			"country": "Equatorial Guinea",
			"telephoneCode": "+240",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 315,
			"countryCode": "ER",
			"country": "Eritrea",
			"telephoneCode": "+291",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 316,
			"countryCode": "EE",
			"country": "Estonia",
			"telephoneCode": "+372",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 317,
			"countryCode": "ET",
			"country": "Ethiopia",
			"telephoneCode": "+251",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 320,
			"countryCode": "FJ",
			"country": "Fiji",
			"telephoneCode": "+679",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 321,
			"countryCode": "FI",
			"country": "Finland",
			"telephoneCode": "+358",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 322,
			"countryCode": "FR",
			"country": "France",
			"telephoneCode": "+33",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 326,
			"countryCode": "GA",
			"country": "Gabon",
			"telephoneCode": "+241",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 327,
			"countryCode": "GM",
			"country": "Gambia",
			"telephoneCode": "+220",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 328,
			"countryCode": "GE",
			"country": "Georgia",
			"telephoneCode": "+995",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 329,
			"countryCode": "DE",
			"country": "Germany",
			"telephoneCode": "+49",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 330,
			"countryCode": "GH",
			"country": "Ghana",
			"telephoneCode": "+233",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 332,
			"countryCode": "GR",
			"country": "Greece",
			"telephoneCode": "+30",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 334,
			"countryCode": "GD",
			"country": "Grenada",
			"telephoneCode": "+1-473",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 337,
			"countryCode": "GT",
			"country": "Guatemala",
			"telephoneCode": "+502",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 339,
			"countryCode": "GN",
			"country": "Guinea",
			"telephoneCode": "+224",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 340,
			"countryCode": "GW",
			"country": "Guinea-Bissau",
			"telephoneCode": "+245",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 341,
			"countryCode": "GY",
			"country": "Guyana",
			"telephoneCode": "+592",
			"countryFlag": "WI-CR1",
			"active": true
		}, {
			"countryId": 342,
			"countryCode": "HT",
			"country": "Haiti",
			"telephoneCode": "+509",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 344,
			"countryCode": "VA",
			"country": "Holy See (Vatican City State)",
			"telephoneCode": "+39-06",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 345,
			"countryCode": "HN",
			"country": "Honduras",
			"telephoneCode": "+504",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 346,
			"countryCode": "HK",
			"country": "Hong Kong",
			"telephoneCode": "+852",
			"countryFlag": "HK-CR1",
			"active": true
		}, {
			"countryId": 347,
			"countryCode": "HU",
			"country": "Hungary",
			"telephoneCode": "+36",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 348,
			"countryCode": "IS",
			"country": "Iceland",
			"telephoneCode": "+354",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 349,
			"countryCode": "ID",
			"country": "Indonesia",
			"telephoneCode": "+62",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 351,
			"countryCode": "IQ",
			"country": "Iraq",
			"telephoneCode": "+964",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 352,
			"countryCode": "IE",
			"country": "Ireland",
			"telephoneCode": "+353",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 354,
			"countryCode": "IL",
			"country": "Israel",
			"telephoneCode": "+972",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 355,
			"countryCode": "IT",
			"country": "Italy",
			"telephoneCode": "+39",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 356,
			"countryCode": "JM",
			"country": "Jamaica",
			"telephoneCode": "+1-876",
			"countryFlag": "WI-CR1",
			"active": true
		}, {
			"countryId": 357,
			"countryCode": "JP",
			"country": "Japan",
			"telephoneCode": "+81",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 359,
			"countryCode": "JO",
			"country": "Jordan",
			"telephoneCode": "+962",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 360,
			"countryCode": "KZ",
			"country": "Kazakhstan",
			"telephoneCode": "+7",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 361,
			"countryCode": "KE",
			"country": "Kenya",
			"telephoneCode": "+254",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 362,
			"countryCode": "KI",
			"country": "Kiribati",
			"telephoneCode": "+686",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 364,
			"countryCode": "KR",
			"country": "South Korea",
			"telephoneCode": "+82",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 365,
			"countryCode": "KW",
			"country": "Kuwait",
			"telephoneCode": "+965",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 366,
			"countryCode": "KG",
			"country": "Kyrgyzstan",
			"telephoneCode": "+996",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 367,
			"countryCode": "LA",
			"country": "Laos",
			"telephoneCode": "+856",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 368,
			"countryCode": "LV",
			"country": "Latvia",
			"telephoneCode": "+371",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 369,
			"countryCode": "LB",
			"country": "Lebanon",
			"telephoneCode": "+961",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 370,
			"countryCode": "LS",
			"country": "Lesotho",
			"telephoneCode": "+266",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 371,
			"countryCode": "LR",
			"country": "Liberia",
			"telephoneCode": "+231",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 372,
			"countryCode": "LY",
			"country": "Libya",
			"telephoneCode": "+218",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 373,
			"countryCode": "LI",
			"country": "Liechtenstein",
			"telephoneCode": "+423",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 374,
			"countryCode": "LT",
			"country": "Lithuania",
			"telephoneCode": "+370",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 375,
			"countryCode": "LU",
			"country": "Luxembourg",
			"telephoneCode": "+352",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 376,
			"countryCode": "MO",
			"country": "Macau",
			"telephoneCode": "+853",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 377,
			"countryCode": "MK",
			"country": "Macedonia",
			"telephoneCode": "+389",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 378,
			"countryCode": "MG",
			"country": "Madagascar",
			"telephoneCode": "+261",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 379,
			"countryCode": "MW",
			"country": "Malawi",
			"telephoneCode": "+265",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 380,
			"countryCode": "MY",
			"country": "Malaysia",
			"telephoneCode": "+60",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 381,
			"countryCode": "MV",
			"country": "Maldives",
			"telephoneCode": "+960",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 382,
			"countryCode": "ML",
			"country": "Mali",
			"telephoneCode": "+223",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 383,
			"countryCode": "MT",
			"country": "Malta",
			"telephoneCode": "+356",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 384,
			"countryCode": "MH",
			"country": "Marshall Islands",
			"telephoneCode": "+692",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 386,
			"countryCode": "MR",
			"country": "Mauritania",
			"telephoneCode": "+222",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 387,
			"countryCode": "MU",
			"country": "Mauritius",
			"telephoneCode": "+230",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 389,
			"countryCode": "MX",
			"country": "Mexico",
			"telephoneCode": "+52",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 390,
			"countryCode": "FM",
			"country": "Micronesia",
			"telephoneCode": "+691",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 391,
			"countryCode": "MD",
			"country": "Moldova",
			"telephoneCode": "+373",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 392,
			"countryCode": "MC",
			"country": "Monaco",
			"telephoneCode": "+377",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 393,
			"countryCode": "MN",
			"country": "Mongolia",
			"telephoneCode": "+976",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 394,
			"countryCode": "ME",
			"country": "Montenegro",
			"telephoneCode": "+382",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 396,
			"countryCode": "MA",
			"country": "Morocco",
			"telephoneCode": "+212",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 397,
			"countryCode": "MZ",
			"country": "Mozambique",
			"telephoneCode": "+258",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 398,
			"countryCode": "MM",
			"country": "Myanmar",
			"telephoneCode": "+95",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 399,
			"countryCode": "NA",
			"country": "Namibia",
			"telephoneCode": "+264",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 400,
			"countryCode": "NR",
			"country": "Nauru",
			"telephoneCode": "+674",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 401,
			"countryCode": "NP",
			"country": "Nepal",
			"telephoneCode": "+977",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 402,
			"countryCode": "NL",
			"country": "Netherlands",
			"telephoneCode": "+31",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 404,
			"countryCode": "NZ",
			"country": "New Zealand",
			"telephoneCode": "+64",
			"countryFlag": "NZ-CR1",
			"active": true
		}, {
			"countryId": 405,
			"countryCode": "NI",
			"country": "Nicaragua",
			"telephoneCode": "+505",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 406,
			"countryCode": "NE",
			"country": "Niger",
			"telephoneCode": "+227",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 407,
			"countryCode": "NG",
			"country": "Nigeria",
			"telephoneCode": "+234",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 411,
			"countryCode": "NO",
			"country": "Norway",
			"telephoneCode": "+47",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 412,
			"countryCode": "OM",
			"country": "Oman",
			"telephoneCode": "+968",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 414,
			"countryCode": "PW",
			"country": "Palau",
			"telephoneCode": "+680",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 415,
			"countryCode": "PS",
			"country": "Palestine",
			"telephoneCode": "+970",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 416,
			"countryCode": "PA",
			"country": "Panama",
			"telephoneCode": "+507",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 417,
			"countryCode": "PG",
			"country": "Papua New Guinea",
			"telephoneCode": "+675",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 418,
			"countryCode": "PY",
			"country": "Paraguay",
			"telephoneCode": "+595",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 419,
			"countryCode": "PE",
			"country": "Peru",
			"telephoneCode": "+51",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 420,
			"countryCode": "PH",
			"country": "Philippines",
			"telephoneCode": "+63",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 422,
			"countryCode": "PL",
			"country": "Poland",
			"telephoneCode": "+48",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 423,
			"countryCode": "PT",
			"country": "Portugal",
			"telephoneCode": "+351",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 425,
			"countryCode": "QA",
			"country": "Qatar",
			"telephoneCode": "+974",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 426,
			"countryCode": "RO",
			"country": "Romania",
			"telephoneCode": "+40",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 428,
			"countryCode": "RW",
			"country": "Rwanda",
			"telephoneCode": "+250",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 432,
			"countryCode": "KN",
			"country": "Saint Kitts And Nevis",
			"telephoneCode": "+1-869",
			"countryFlag": "WI-CR1",
			"active": true
		}, {
			"countryId": 433,
			"countryCode": "LC",
			"country": "Saint Lucia",
			"telephoneCode": "+1",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 436,
			"countryCode": "VC",
			"country": "Saint Vincent And The Grenadines",
			"telephoneCode": "+1-784",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 437,
			"countryCode": "WS",
			"country": "Samoa",
			"telephoneCode": "+685",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 438,
			"countryCode": "SM",
			"country": "San Marino",
			"telephoneCode": "+378",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 439,
			"countryCode": "ST",
			"country": "Sao Tome And Principe",
			"telephoneCode": "+239",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 440,
			"countryCode": "SA",
			"country": "Saudi Arabia",
			"telephoneCode": "+966",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 441,
			"countryCode": "SN",
			"country": "Senegal",
			"telephoneCode": "+221",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 442,
			"countryCode": "RS",
			"country": "Serbia",
			"telephoneCode": "+381",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 443,
			"countryCode": "SC",
			"country": "Seychelles",
			"telephoneCode": "+248",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 444,
			"countryCode": "SL",
			"country": "Sierra Leone",
			"telephoneCode": "+232",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 445,
			"countryCode": "SG",
			"country": "Singapore",
			"telephoneCode": "+65",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 447,
			"countryCode": "SK",
			"country": "Slovakia",
			"telephoneCode": "+421",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 448,
			"countryCode": "SI",
			"country": "Slovenia",
			"telephoneCode": "+386",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 449,
			"countryCode": "SB",
			"country": "Solomon Islands",
			"telephoneCode": "+677",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 450,
			"countryCode": "SO",
			"country": "Somalia",
			"telephoneCode": "+252",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 451,
			"countryCode": "ZA",
			"country": "South Africa",
			"telephoneCode": "+27",
			"countryFlag": "RSA-CR1",
			"active": true
		}, {
			"countryId": 453,
			"countryCode": "SS",
			"country": "South Sudan",
			"telephoneCode": "+211",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 454,
			"countryCode": "ES",
			"country": "Spain",
			"telephoneCode": "+34",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 455,
			"countryCode": "LK",
			"country": "Sri Lanka",
			"telephoneCode": "+94",
			"countryFlag": "SRI-CR1",
			"active": true
		}, {
			"countryId": 456,
			"countryCode": "SD",
			"country": "Sudan",
			"telephoneCode": "+249",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 457,
			"countryCode": "SR",
			"country": "Suriname",
			"telephoneCode": "+597",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 459,
			"countryCode": "SZ",
			"country": "Swaziland",
			"telephoneCode": "+268",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 460,
			"countryCode": "SE",
			"country": "Sweden",
			"telephoneCode": "+46",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 461,
			"countryCode": "CH",
			"country": "Switzerland",
			"telephoneCode": "+41",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 463,
			"countryCode": "TW",
			"country": "Taiwan",
			"telephoneCode": "+886",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 464,
			"countryCode": "TJ",
			"country": "Tajikistan",
			"telephoneCode": "+992",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 465,
			"countryCode": "TZ",
			"country": "United Republic Of Tanzania",
			"telephoneCode": "+255",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 466,
			"countryCode": "TH",
			"country": "Thailand",
			"telephoneCode": "+66",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 467,
			"countryCode": "TL",
			"country": "Timor-Leste",
			"telephoneCode": "+670",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 468,
			"countryCode": "TG",
			"country": "Togo",
			"telephoneCode": "+228",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 470,
			"countryCode": "TO",
			"country": "Tonga",
			"telephoneCode": "+676",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 471,
			"countryCode": "TT",
			"country": "Trinidad And Tobago",
			"telephoneCode": "+1-868",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 472,
			"countryCode": "TN",
			"country": "Tunisia",
			"telephoneCode": "+216",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 473,
			"countryCode": "TR",
			"country": "Turkey",
			"telephoneCode": "+90",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 474,
			"countryCode": "TM",
			"country": "Turkmenistan",
			"telephoneCode": "+993",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 476,
			"countryCode": "TV",
			"country": "Tuvalu",
			"telephoneCode": "+688",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 477,
			"countryCode": "UG",
			"country": "Uganda",
			"telephoneCode": "+256",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 478,
			"countryCode": "UA",
			"country": "Ukraine",
			"telephoneCode": "+380",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 479,
			"countryCode": "AE",
			"country": "United Arab Emirates",
			"telephoneCode": "+971",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 480,
			"countryCode": "GB",
			"country": "United Kingdom",
			"telephoneCode": "+44",
			"countryFlag": "ENG-CR1",
			"active": true
		}, {
			"countryId": 482,
			"countryCode": "UY",
			"country": "Uruguay",
			"telephoneCode": "+598",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 483,
			"countryCode": "UZ",
			"country": "Uzbekistan",
			"telephoneCode": "+998",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 484,
			"countryCode": "VU",
			"country": "Vanuatu",
			"telephoneCode": "+678",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 485,
			"countryCode": "VE",
			"country": "Venezuela",
			"telephoneCode": "+58",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 486,
			"countryCode": "VN",
			"country": "Vietnam",
			"telephoneCode": "+84",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 491,
			"countryCode": "YE",
			"country": "Yemen",
			"telephoneCode": "+967",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 492,
			"countryCode": "ZM",
			"country": "Zambia",
			"telephoneCode": "+260",
			"countryFlag": null,
			"active": true
		}, {
			"countryId": 493,
			"countryCode": "ZW",
			"country": "Zimbabwe",
			"telephoneCode": "+263",
			"countryFlag": null,
			"active": true
		}]
	});
}
